from PyQt5 import QtCore, QtGui, QtWidgets


class LoginUi(object):
    def setup_ui(self, window):
        self.window = window
        self.window.setObjectName("Window")
        self.window.resize(320, 0)
        self.window.setWindowTitle("Chat Login")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout1")
        self.labelName = QtWidgets.QLabel(self.window)
        self.labelName.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.labelName.setObjectName("labelName")
        self.labelName.setText("Name:")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelName)
        self.lineName = QtWidgets.QLineEdit(self.window)
        self.lineName.setClearButtonEnabled(True)
        self.lineName.setObjectName("lineName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineName)
        self.verticalLayout.addLayout(self.formLayout)

        self.labelError = QtWidgets.QLabel(self.window)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelError.setPalette(palette)
        self.labelError.setObjectName("labelError")
        self.verticalLayout.addWidget(self.labelError)

        self.line = QtWidgets.QFrame(self.window)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout2 = QtWidgets.QFormLayout()
        self.formLayout2.setObjectName("formLayout2")
        self.labelPort = QtWidgets.QLabel(self.window)
        self.labelPort.setObjectName("labelPort")
        self.labelPort.setText("Port:")
        self.formLayout2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPort)
        self.spinPort = QtWidgets.QSpinBox(self.window)
        self.spinPort.setMaximum(65535)
        self.spinPort.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinPort.setDisplayIntegerBase(10)
        self.spinPort.setObjectName("spinPort")
        self.formLayout2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinPort)
        self.labelIP = QtWidgets.QLabel(self.window)
        self.labelIP.setObjectName("labelIP")
        self.labelIP.setText("IP Address:")
        self.formLayout2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelIP)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineIP = QtWidgets.QLineEdit(self.window)
        self.lineIP.setText("")
        self.lineIP.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lineIP.setObjectName("lineIP")
        self.horizontalLayout.addWidget(self.lineIP)
        self.formLayout2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.window)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Close | QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.labelName.setBuddy(self.lineName)
        self.labelPort.setBuddy(self.spinPort)
        self.labelIP.setBuddy(self.lineIP)

        QtCore.QMetaObject.connectSlotsByName(self.window)
        self.window.setTabOrder(self.lineName, self.lineIP)
        self.window.setTabOrder(self.lineIP, self.spinPort)

        # make Reset button restore all inputs to default state:
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Reset).clicked.connect(self.lineName.clear)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Reset).clicked.connect(self.lineIP.clear)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Reset).clicked.connect(self.labelError.clear)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Reset).clicked.connect(lambda: self.spinPort.setValue(8000))
        self.buttonBox.rejected.connect(self.window.close)  # Close button quits window

    def ok(self):
        QtWidgets.QApplication.setOverrideCursor(QtCore.Qt.WaitCursor)
        self.lineIP.setReadOnly(True)
        self.lineName.setReadOnly(True)
        self.spinPort.setReadOnly(True)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Reset).setEnabled(False)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setEnabled(False)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Close).setFocus()

    def retry(self):
        QtWidgets.QApplication.restoreOverrideCursor()
        self.lineIP.setReadOnly(False)
        self.lineName.setReadOnly(False)
        self.spinPort.setReadOnly(False)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Reset).setEnabled(True)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setEnabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QDialog()
    ui = LoginUi()
    ui.setup_ui(window)
    Window.show()
    sys.exit(app.exec_())
